### PR TITLE
Symfony 6

### PR DESCRIPTION
**Pull request by ruudk**
Based on https://github.com/broadway/broadway-bundle/pull/94

Blocked by:
- https://github.com/malukenho/docheader/pull/35

### CODE REVIEW

**Comment by ruudk** [comment]
@othillo Why is there a dependency on docheader anyway?

**Comment by ruudk** [comment]
while looking at what https://github.com/broadway/coding-standard actually tries to do, I don't get it. This simple config can just be copied into this project and be done. No transitive dependency management.

**Comment by othillo** [comment]
@ruudk feel free to remove `docheader`. Before migrating to GitHub Actions we used it in a Travis CI step to enforce doc headers in all files. But I never ported that and now it's just in the way.

**Comment by ruudk** [comment]
Can I drop the coding standard dependency, and copy the cs fix config into the repo ?

**Comment by ruudk** [comment]
Ready

**Comment by othillo** [comment]
> Can I drop the coding standard dependency, and copy the cs fix config into the repo ?

And add php-cs-fixer as a dev dependency here?
Hmm, mixed emotions. But I think it's more important now to just get this bundle compatible with Symfony 6 than to cling to an (outdated) code reuse. So please, go ahead!

**Comment by ruudk** [comment]
Well, it was already a dev dependency via https://github.com/broadway/coding-standard/blob/master/composer.json#L13

**Review by othillo — APPROVED** [review]

**Comment by ruudk** [comment]
Thanks for the fast merge ⚡

**Comment by othillo** [comment]
Thank you very much, @ruudk !

**Pull request merged**
