### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by morawskim**

### CODE REVIEW

**Comment by matiux** [comment]
Hi @morawskim, thanks for this PR. Any news?

**Comment by morawskim** [comment]
Hello @matiux 
From my point of view this PR is ready.
I use broadway-bundle with Symfony 7 and it works.

**Comment by wjzijderveld** [comment]
Sorry, I totally missed this! 
Could you rebase so the CI triggers? It seems it was paused when you submitted it and I don't have a way to manually trigger it again it seems :thinking: 

I think we should drop some of the Symfony and PHP versions from the matrix, to keep it manageable, but I'll do that separately.

**Comment by morawskim** [comment]
@wjzijderveld 
It is ok. I will rebase the PR tomorrow.

**Comment by morawskim** [comment]
@wjzijderveld 
Done. 
I  had to modify `.github/workflows/ci.yml`, otherwise not all tests would pass.
It looks like that you need to allow to run workflow, due to security reason.

**Review by wjzijderveld — APPROVED** [review]

**Comment by wjzijderveld** [comment]
Thank you @morawskim !

**Pull request merged**
