### PR TITLE
update supported Symfony versions

### PR DESCRIPTION
**Pull request by othillo**
see https://github.com/broadway/broadway-bundle/issues/92

### CODE REVIEW

**Comment by ruudk** [comment]
@othillo Do you need help with this?

**Comment by othillo** [comment]
> @othillo Do you need help with this?
Oh, yes, please!

**Comment by ruudk** [comment]
On it

**Comment by ruudk** [comment]
@othillo https://github.com/broadway/broadway-bundle/pull/94

**Pull request closed without merging**
